name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- feature/*
- release/*
- hotfix/*
- develop
- master

resources:
  repositories:
    - repository: common-pipeline-template-aks
      type: git
      name: BP-DevOps-Infrastructure/common-pipeline-template-aks
      ref: refs/heads/master

variables:
- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/') }}:
  - group: development
- ${{ if or( eq(variables['Build.SourceBranch'], 'refs/heads/develop'),startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
  - group: development
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - group: development

extends:
  template: javascript/nestjs/yarn/init.yml@common-pipeline-template-aks